path: /Users/lsv/Downloads/implementacion_yolov8/datasets
train: navegadores/images/train
val: navegadores/images/train

names: 
  0: 'Buttons'
  1: 'Cells'
  2: 'Checkbox'
  3: 'DropDownList'
  4: 'HamburgerButton'
  5: 'Icon'
  6: 'ListBoxes'
  7: 'ProgressBar'
  8: 'RadioButton'
  9: 'SearchBox'
  10: 'Submenu'
  11: 'TextFields'
  12: 'Toggles'